name: Build-Step

on: push

jobs:
  build-step:
    name: Perform Normal Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Deps
        run: ./scripts/install_deps.sh

      - name: Install System Deps
        run: ./scripts/install_sys_deps.sh

      - name: Build Project
        run: ./build.sh

